import = ["~/.config/alacritty/themes/tokyo-night.toml"]

live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[font]
offset = { x = 0, y = 10 }
normal = { family = "JetBrains Mono", style = "Regular" }
bold = { family = "JetBrains Mono", style = "Bold" }
italic = { family = "JetBrains Mono", style = "Italic" }
size = 14.0
glyph_offset = { x = 0, y = 0 }

#change cursor type Beam,Block,Underline
[cursor]
style = "Block"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

#startup modes:Windowed, Maximized, Fullscreen
[window]
dynamic_padding = false
opacity = 1
title = "Alacritty"
startup_mode = "Maximized"
class = { general = "Alacritty", instance = "Alacritty" }
padding = { x = 4, y = 0 }
